"""
flow._client — High-level FlowClient combining FlowAPI + FlowUI + UIInterceptor.

Architecture:
    FlowAPI        → direct REST/tRPC calls (credits, poll, model config) — NO reCAPTCHA
    FlowUI         → Playwright UI automation (navigate, click buttons, fill inputs)
    UIInterceptor  → captures aisandbox API calls triggered by UI clicks (gets valid reCAPTCHA)
    FlowClient     → combines all three into clean async methods

The key insight:
    All generation endpoints need valid reCAPTCHA Enterprise tokens.
    Tokens from page.evaluate() are rejected (Playwright detected → low score).
    Tokens generated by REAL button clicks PASS.
    Solution: click buttons, intercept the resulting API call.

Usage:
    async with await FlowClient.create("project-uuid") as client:
        job = await client.generate_video("golden lotus at dawn")
        status = await client.wait_for_video(job)
        path = await client.download(status.media_name, "./output/video.mp4")
"""
from __future__ import annotations

import asyncio
import logging
import time
from pathlib import Path
from typing import Optional

from ._api import FlowAPI, VideoJob, VideoStatus, GeneratedImage, Credits, Workflow
from ._browser import BrowserManager
from ._exceptions import (
    AuthError, GenerationError, GenerationTimeout,
    InvalidArgumentError, NotFoundError,
)
from ._flow_ui import FlowUI
from ._models import AspectRatio, GenerationMode
from ._storage import get_active_project, load_config, set_active_project
from ._ui_interceptor import UIInterceptor

log = logging.getLogger(__name__)

# ── Camera motion constants ────────────────────────────────────────────────────
CAMERA_MOTIONS = {
    "dolly_in":          "Dolly in",
    "dolly-in":          "Dolly in",
    "dolly_out":         "Dolly out",
    "dolly-out":         "Dolly out",
    "orbit_left":        "Orbit left",
    "orbit-left":        "Orbit left",
    "orbit_right":       "Orbit right",
    "orbit-right":       "Orbit right",
    "orbit_up":          "Orbit up",
    "orbit-up":          "Orbit up",
    "orbit_low":         "Orbit low",
    "orbit-low":         "Orbit low",
    "dolly_zoom_in":     "Dolly in zoom out",
    "dolly-zoom-in":     "Dolly in zoom out",
    "dolly_zoom_out":    "Dolly out zoom in",
    "dolly-zoom-out":    "Dolly out zoom in",
}

CAMERA_POSITIONS = {
    "center":  "Center",
    "left":    "Left",
    "right":   "Right",
    "high":    "High",
    "low":     "Low",
    "closer":  "Closer",
    "further": "Further",
}


class FlowClient:
    """
    High-level async client for Google Flow AI.

    All generation methods use UI automation + network interception to get
    valid reCAPTCHA tokens (required by aisandbox-pa.googleapis.com).

    Read-only methods (credits, poll, model_config) use the direct REST API.
    """

    def __init__(
        self,
        api: FlowAPI,
        bm: BrowserManager,
        project_id: str,
        workflow_id: Optional[str] = None,
    ):
        self._api       = api
        self._bm        = bm
        self.project_id = project_id
        self.workflow_id = workflow_id
        self._ui        = FlowUI()
        self._project_url = f"https://flow.google.com/project/{project_id}"

    # ── Factory ────────────────────────────────────────────────────────────────

    @classmethod
    async def create(
        cls,
        project_id: Optional[str] = None,
        workflow_id: Optional[str] = None,
        *,
        headless: bool = True,
        cdp_url: Optional[str] = None,
        timeout_s: int = 300,
    ) -> "FlowClient":
        """
        Create and initialize a FlowClient.

        Args:
            project_id:  Flow project UUID. Defaults to the saved active project.
            workflow_id: Flow workflow UUID (used for edit-page operations).
            headless:    Launch browser in headless mode (default True).
            cdp_url:     Connect to an existing Chrome CDP port, e.g. "http://127.0.0.1:9222".
                         Useful in development; bypasses login but reCAPTCHA may fail.
            timeout_s:   Default generation timeout (seconds).
        """
        cfg = load_config()
        pid = project_id or get_active_project()[0] or ""

        if cdp_url:
            bm = BrowserManager.from_cdp(cdp_url)
        else:
            bm = BrowserManager(headless=headless)
        await bm.start()

        api = FlowAPI(bm, project_id=pid, default_timeout_s=timeout_s)

        # Navigate to project page to load session + reCAPTCHA
        page = await bm.page()
        if "flow.google.com" not in page.url and "labs.google" not in page.url:
            proj_url = f"https://flow.google.com/project/{pid}"
            await page.goto(proj_url, wait_until="domcontentloaded", timeout=20_000)
            await asyncio.sleep(2)

        return cls(api, bm, pid, workflow_id)

    # ── Context manager ────────────────────────────────────────────────────────

    async def __aenter__(self):
        return self

    async def __aexit__(self, *_):
        await self.close()

    async def close(self):
        await self._bm.stop()

    # ══════════════════════════════════════════════════════════════════════════
    # GENERATION (UI automation + interceptor)
    # ══════════════════════════════════════════════════════════════════════════

    async def generate_video(
        self,
        prompt: str,
        *,
        model: str = "Veo 3.1 - Fast",
        aspect: str = "landscape",
        count: int = 1,
        start_image: Optional[str] = None,
        workflow_id: Optional[str] = None,
        timeout_s: int = 120,
    ) -> list[VideoJob]:
        """
        Generate video(s) from a text prompt (T2V or I2V).

        The UI workflow:
          1. Navigate to project page
          2. (Optionally) upload start_image for I2V mode
          3. Open settings: set Video mode, aspect ratio, count
          4. Fill prompt
          5. Click Create → captures batchAsyncGenerateVideoText response

        Args:
            prompt:     Generation prompt text
            model:      Display name of the video model (used in dropdown)
            aspect:     "landscape" or "portrait"
            count:      Number of videos to generate (1-4)
            start_image: Local path to an image for I2V (Image-to-Video) mode
            timeout_s:  Seconds to wait for the API call

        Returns:
            List of VideoJob objects (PENDING status, use wait_for_video to poll)
        """
        page = await self._bm.page()
        await self._ensure_project_page(page)

        interceptor = UIInterceptor()
        interceptor.attach(page)

        # Configure settings
        await self._ui.open_settings_panel(page)
        mode = GenerationMode.FRAME_TO_VIDEO if start_image else GenerationMode.VIDEO
        await self._ui.switch_mode(page, mode)
        ratio = AspectRatio.PORTRAIT if aspect == "portrait" else AspectRatio.LANDSCAPE
        await self._ui.set_aspect_ratio(page, ratio)
        await self._ui.set_count(page, count)
        await self._ui.fill_prompt(page, prompt)

        if start_image:
            await self._ui.upload_image(page, start_image)

        # Click submit → triggers real reCAPTCHA token generation
        await self._ui.click_submit(page)

        # Wait for API response
        entry = await interceptor.wait_for(
            "batchAsyncGenerateVideoText", timeout=timeout_s, require_success=True
        )

        jobs = []
        for job_data in entry.resp.get("jobs", []):
            media_id = job_data.get("mediaId", {})
            media_name = media_id.get("mediaName") or media_id.get("name", "")
            job = VideoJob.__new__(VideoJob)
            job.media_name = media_name
            job.status = "PENDING"
            job.project_id = self.project_id
            jobs.append(job)

        log.info("T2V submitted: %d job(s)", len(jobs))
        return jobs

    async def generate_image(
        self,
        prompt: str,
        *,
        aspect: str = "landscape",
        count: int = 1,
        reference_images: Optional[list[str]] = None,
        timeout_s: int = 120,
    ) -> list[GeneratedImage]:
        """
        Generate images from a text prompt (T2I).

        Returns list of GeneratedImage with fife_url for display/download.
        Image generation is synchronous (waits 45-60s for server to generate).

        Uses the same UI as video generation but with Image mode selected.
        Endpoint: batchGenerateImages (returns immediately with image data).
        
        Note: Settings panel can be unreliable. If switch_mode fails, manually
        click an image thumbnail first to enter image edit mode, then call this.
        """
        page = await self._bm.page()
        await self._ensure_project_page(page)

        interceptor = UIInterceptor()
        interceptor.attach(page)

        await self._ui.open_settings_panel(page)
        await self._ui.switch_mode(page, GenerationMode.IMAGE)
        ratio = (AspectRatio.PORTRAIT if "port" in aspect else
                 AspectRatio.SQUARE   if "square" in aspect else
                 AspectRatio.LANDSCAPE)
        await self._ui.set_aspect_ratio(page, ratio)
        await self._ui.set_count(page, count)
        await self._ui.fill_prompt(page, prompt)
        await self._ui.click_submit(page)

        entry = await interceptor.wait_for(
            "batchGenerateImages", timeout=timeout_s, require_success=True
        )

        images = []
        for item in entry.resp.get("media", []):
            gen = item.get("image", {}).get("generatedImage", {})
            img = GeneratedImage.__new__(GeneratedImage)
            img.fife_url   = gen.get("fifeUrl", "")
            img.media_name = item.get("name", "")
            img.prompt     = gen.get("prompt", prompt)
            img.seed       = gen.get("seed")
            img.dimensions = item.get("dimensions", {})
            images.append(img)

        log.info("T2I complete: %d image(s)", len(images))
        return images

    # ── Edit-page operations ──────────────────────────────────────────────────

    async def extend_video(
        self,
        media_id: str,
        workflow_id: Optional[str] = None,
        prompt: str = "",
        *,
        timeout_s: int = 120,
    ) -> VideoJob:
        """
        Extend a video to make it longer.

        Navigates to the edit page, clicks Extend, optionally fills a prompt,
        clicks Create, and returns a PENDING VideoJob.

        Uses endpoint: batchAsyncGenerateVideoExtendVideo
        Model: veo_3_1_extend_fast_landscape
        Cost: same as T2V (uses credits)
        """
        wid = workflow_id or self.workflow_id or ""
        page = await self._bm.page()
        await self._ui.navigate_to_edit(page, self.project_id, wid)

        interceptor = UIInterceptor()
        interceptor.attach(page)

        await self._ui.click_extend(page)
        await self._ui.fill_extend_prompt(page, prompt or "Continue the scene")
        await self._ui.click_create_in_panel(page)

        entry = await interceptor.wait_for(
            "batchAsyncGenerateVideoExtendVideo", timeout=timeout_s, require_success=True
        )

        media_name = UIInterceptor.extract_video_media_name(entry.resp) or ""
        job = VideoJob.__new__(VideoJob)
        job.media_name = media_name
        job.status = "PENDING"
        job.project_id = self.project_id
        log.info("Extend submitted → %s", media_name[:16])
        return job

    async def extend_loop(
        self,
        media_id: str,
        workflow_id: Optional[str] = None,
        iterations: int = 5,
        prompt: str = "",
        output_dir: Optional[str] = None,
        *,
        wait: bool = True,
        poll_s: float = 5.0,
        timeout_s: int = 300,
    ) -> list[VideoJob]:
        """
        Extend a video *iterations* times in sequence → create arbitrarily long videos!

        Each extension takes the result of the previous as input.
        The workflow_id stays constant (points to the original workflow);
        the mediaId advances with each extension.

        Args:
            media_id:    Starting media UUID
            workflow_id: Workflow UUID
            iterations:  Number of extensions (e.g. 10 = ~80 seconds of video)
            prompt:      Optional narrative prompt for each extension
            output_dir:  If set, downloads each extended video here
            wait:        Wait for each extension before starting the next
            poll_s:      Poll interval when waiting
            timeout_s:   Per-extension generation timeout

        Returns:
            List of VideoJob (all PENDING if wait=False, all complete if wait=True)
        """
        jobs: list[VideoJob] = []
        current_id = media_id
        out = Path(output_dir) if output_dir else None
        if out:
            out.mkdir(parents=True, exist_ok=True)

        for i in range(iterations):
            log.info("Extend loop %d/%d, media=%s", i + 1, iterations, current_id[:12])
            job = await self.extend_video(current_id, workflow_id, prompt, timeout_s=timeout_s)
            jobs.append(job)

            if wait:
                status = await self.wait_for_video(job, poll_s=poll_s, timeout_s=timeout_s)
                current_id = job.media_name or current_id
                if out and status.fife_url:
                    dest = out / f"extend_{i+1:03d}.mp4"
                    await self.download(status.fife_url, dest)
                    log.info("  → saved %s", dest)
            else:
                current_id = job.media_name or current_id

        return jobs

    async def camera_motion(
        self,
        media_id: str,
        motion: str,
        workflow_id: Optional[str] = None,
        *,
        timeout_s: int = 120,
    ) -> VideoJob:
        """
        Apply a camera motion to a video.

        Args:
            media_id: Source video media UUID
            motion:   Motion key. Supported values:
                        "dolly_in", "dolly_out",
                        "orbit_left", "orbit_right", "orbit_up", "orbit_low",
                        "dolly_zoom_in", "dolly_zoom_out"
            workflow_id: Workflow UUID

        Uses endpoint: batchAsyncGenerateVideoReshootVideo
        Model: veo_3_0_reshoot_landscape
        """
        motion_label = CAMERA_MOTIONS.get(motion.lower(), motion)
        wid = workflow_id or self.workflow_id or ""
        page = await self._bm.page()
        await self._ui.navigate_to_edit(page, self.project_id, wid)

        interceptor = UIInterceptor()
        interceptor.attach(page)

        await self._ui.click_camera(page)
        await self._ui.select_camera_motion(page, motion_label)
        await self._ui.click_camera_create(page)

        entry = await interceptor.wait_for(
            "batchAsyncGenerateVideoReshootVideo", timeout=timeout_s, require_success=True
        )

        media_name = UIInterceptor.extract_video_media_name(entry.resp) or ""
        job = VideoJob.__new__(VideoJob)
        job.media_name = media_name
        job.status = "PENDING"
        job.project_id = self.project_id
        log.info("Camera motion '%s' submitted → %s", motion, media_name[:16])
        return job

    async def camera_position(
        self,
        media_id: str,
        position: str,
        workflow_id: Optional[str] = None,
        *,
        timeout_s: int = 120,
    ) -> VideoJob:
        """
        Apply a camera position change to a video.

        Args:
            position: "center", "left", "right", "high", "low", "closer", "further"

        Uses the same ReshootVideo endpoint with STATIONARY_* motion types.
        """
        pos_label = CAMERA_POSITIONS.get(position.lower(), position.title())
        wid = workflow_id or self.workflow_id or ""
        page = await self._bm.page()
        await self._ui.navigate_to_edit(page, self.project_id, wid)

        interceptor = UIInterceptor()
        interceptor.attach(page)

        await self._ui.click_camera(page)
        await self._ui.select_camera_position(page, pos_label)
        await self._ui.click_camera_create(page)

        entry = await interceptor.wait_for(
            "batchAsyncGenerateVideoReshootVideo", timeout=timeout_s, require_success=True
        )

        media_name = UIInterceptor.extract_video_media_name(entry.resp) or ""
        job = VideoJob.__new__(VideoJob)
        job.media_name = media_name
        job.status = "PENDING"
        job.project_id = self.project_id
        log.info("Camera position '%s' submitted → %s", position, media_name[:16])
        return job

    async def insert_object(
        self,
        media_id: str,
        prompt: str,
        workflow_id: Optional[str] = None,
        *,
        timeout_s: int = 120,
    ) -> VideoJob:
        """
        Insert an object into a video using a text prompt.

        Uses endpoint: batchAsyncGenerateVideoObjectInsertion
        Model: veo_2_0_object_insertion_landscape
        """
        wid = workflow_id or self.workflow_id or ""
        page = await self._bm.page()
        await self._ui.navigate_to_edit(page, self.project_id, wid)

        interceptor = UIInterceptor()
        interceptor.attach(page)

        await self._ui.click_insert(page)
        if prompt:
            await self._ui.fill_insert_prompt(page, prompt)
        await self._ui.click_create_in_panel(page)

        entry = await interceptor.wait_for(
            "batchAsyncGenerateVideoObjectInsertion", timeout=timeout_s, require_success=True
        )

        media_name = UIInterceptor.extract_video_media_name(entry.resp) or ""
        job = VideoJob.__new__(VideoJob)
        job.media_name = media_name
        job.status = "PENDING"
        job.project_id = self.project_id
        log.info("Insert submitted → %s", media_name[:16])
        return job

    async def remove_object(
        self,
        media_id: str,
        workflow_id: Optional[str] = None,
        *,
        mask_x: float = 0.5,
        mask_y: float = 0.5,
        brush_size: int = 40,
        timeout_s: int = 120,
    ) -> VideoJob:
        """
        Remove an object from a video by drawing a mask.

        Click Remove, draw brush strokes over the object to create the mask,
        then click Create.

        Args:
            mask_x:     Horizontal center of mask (0.0=left, 1.0=right)
            mask_y:     Vertical center of mask (0.0=top, 1.0=bottom)
            brush_size: Brush radius in pixels

        Uses endpoint: batchAsyncGenerateVideoObjectRemoval
        Model: veo_2_0_object_removal_landscape
        """
        wid = workflow_id or self.workflow_id or ""
        page = await self._bm.page()
        await self._ui.navigate_to_edit(page, self.project_id, wid)

        interceptor = UIInterceptor()
        interceptor.attach(page)

        await self._ui.click_remove(page)
        await self._ui.draw_removal_mask(page, mask_x, mask_y, brush_size / 100.0)
        await self._ui.click_create_in_panel(page)

        entry = await interceptor.wait_for(
            "batchAsyncGenerateVideoObjectRemoval", timeout=timeout_s, require_success=True
        )

        media_name = UIInterceptor.extract_video_media_name(entry.resp) or ""
        job = VideoJob.__new__(VideoJob)
        job.media_name = media_name
        job.status = "PENDING"
        job.project_id = self.project_id
        log.info("Remove submitted → %s", media_name[:16])
        return job

    async def upscale_video(
        self,
        media_id: str,
        workflow_id: Optional[str] = None,
        resolution: str = "1080p",
        *,
        timeout_s: int = 120,
    ) -> VideoJob:
        """
        Upscale a video to higher resolution.

        FREE (0 credits)! Uses the Download panel → click "1080p Upscaled".

        Args:
            resolution: "1080p" (free) or "4k" (may require upgrade)

        Uses endpoint: batchAsyncGenerateVideoUpsampleVideo
        Model: veo_3_1_upsampler_1080p
        Cost: 0 credits (FREE!)
        """
        wid = workflow_id or self.workflow_id or ""
        page = await self._bm.page()
        await self._ui.navigate_to_edit(page, self.project_id, wid)

        interceptor = UIInterceptor()
        interceptor.attach(page)

        await self._ui.click_download_button(page)
        await asyncio.sleep(0.5)
        if resolution.lower() in ("4k", "4096"):
            await self._ui.click_upscale_4k(page)
        else:
            await self._ui.click_upscale_1080p(page)

        entry = await interceptor.wait_for(
            "batchAsyncGenerateVideoUpsampleVideo", timeout=timeout_s, require_success=True
        )

        media_name = UIInterceptor.extract_video_media_name(entry.resp) or ""
        # Upscale returns: original_media_id + "_upsampled"
        if not media_name:
            media_name = f"{media_id}_upsampled"

        job = VideoJob.__new__(VideoJob)
        job.media_name = media_name
        job.status = "PENDING"
        job.project_id = self.project_id
        log.info("Upscale submitted → %s (FREE!)", media_name[:20])
        return job

    # ══════════════════════════════════════════════════════════════════════════
    # READ-ONLY OPERATIONS (direct API, no UI)
    # ══════════════════════════════════════════════════════════════════════════

    async def get_credits(self) -> Credits:
        """Get remaining credits. Direct API, no reCAPTCHA needed."""
        return await self._api.get_credits()

    async def poll_video(self, media_id: str) -> VideoStatus:
        """Poll video generation status. Direct API, no reCAPTCHA needed."""
        return await self._api.poll_video(media_id)

    async def wait_for_video(
        self,
        job: VideoJob,
        *,
        poll_s: float = 5.0,
        timeout_s: int = 300,
        on_poll: Optional[callable] = None,
    ) -> VideoStatus:
        """
        Poll until the video is complete.

        Args:
            job:       VideoJob returned by a generation method
            poll_s:    Seconds between polls
            timeout_s: Maximum wait time
            on_poll:   Optional callback(status, elapsed_s) for progress display

        Returns:
            VideoStatus with .complete=True and .fife_url populated
        """
        return await self._api.wait_for_video(job, poll_s=poll_s, timeout_s=timeout_s, on_poll=on_poll)

    async def get_model_config(self) -> dict:
        """Get all video models with costs and capabilities."""
        return await self._api.get_video_model_config()

    async def get_flow_config(self) -> dict:
        """Get Flow app feature flags."""
        return await self._api.get_flow_app_config()

    async def get_workflows(self) -> list[Workflow]:
        """List workflows in the active project."""
        return await self._api.list_workflows()

    # ══════════════════════════════════════════════════════════════════════════
    # DOWNLOAD
    # ══════════════════════════════════════════════════════════════════════════

    async def download(
        self,
        media_name_or_url: str,
        output_path: str | Path,
    ) -> Path:
        """
        Download a generated video or image.

        Args:
            media_name_or_url: FIFE URL (starts with https://lh3.google...) or media UUID
            output_path:       Local file path to save to

        Returns:
            Path object of the saved file
        """
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)

        if media_name_or_url.startswith("https://"):
            url = media_name_or_url
        else:
            # It's a media name → poll to get the fife_url
            status = await self.poll_video(media_name_or_url)
            url = status.fife_url
            if not url:
                raise ValueError(f"No download URL for media {media_name_or_url}")

        return await self._api.download(url, str(out))

    async def download_all(
        self,
        workflow_id: Optional[str] = None,
        output_dir: str | Path = "./flow_output",
        *,
        file_prefix: str = "video",
    ) -> list[Path]:
        """
        Download all completed videos in a workflow.

        Returns list of downloaded paths.
        """
        # Get workflow media list
        wid = workflow_id or self.workflow_id or ""
        data = await self._api.get_project_data()
        workflows = data.get("workflows", [])
        media_names = []
        for wf in workflows:
            if wf.get("id") == wid or not wid:
                for clip in wf.get("clips", []):
                    name = clip.get("mediaId") or clip.get("mediaName")
                    if name:
                        media_names.append(name)

        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        paths = []
        for i, name in enumerate(media_names):
            try:
                status = await self.poll_video(name)
                if status.fife_url:
                    p = out / f"{file_prefix}_{i+1:03d}.mp4"
                    await self.download(status.fife_url, p)
                    paths.append(p)
            except Exception as e:
                log.warning("Could not download %s: %s", name[:16], e)

        return paths

    # ══════════════════════════════════════════════════════════════════════════
    # CONVENIENCE
    # ══════════════════════════════════════════════════════════════════════════

    async def generate_video_and_wait(
        self,
        prompt: str,
        output_path: Optional[str] = None,
        **kwargs,
    ) -> VideoStatus:
        """
        Generate a video and wait for completion. Optionally download.

        Returns VideoStatus with .fife_url and .complete=True.
        """
        jobs = await self.generate_video(prompt, **kwargs)
        if not jobs:
            raise GenerationError("No jobs returned from generate_video")
        status = await self.wait_for_video(jobs[0])
        if output_path and status.fife_url:
            await self.download(status.fife_url, output_path)
        return status

    async def generate_image_and_save(
        self,
        prompt: str,
        output_dir: str = "./flow_images",
        **kwargs,
    ) -> list[Path]:
        """
        Generate images and save them locally.

        Returns list of saved file paths.
        """
        images = await self.generate_image(prompt, **kwargs)
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        paths = []
        for i, img in enumerate(images):
            if img.fife_url:
                p = out / f"image_{i+1:03d}.jpg"
                await self.download(img.fife_url, p)
                paths.append(p)
        return paths

    # ── Private helpers ────────────────────────────────────────────────────────

    async def _ensure_project_page(self, page=None) -> None:
        """Navigate to the project page if not already there."""
        if page is None:
            page = await self._bm.page()
        if self.project_id not in page.url:
            await page.goto(
                self._project_url, wait_until="domcontentloaded", timeout=20_000
            )
            await asyncio.sleep(2)

    def __repr__(self):
        return (
            f"<FlowClient project={self.project_id[:8]}... "
            f"workflow={self.workflow_id and self.workflow_id[:8]}...>"
        )
