"""
flow._ui_interceptor — Network request interceptor for Flow AI UI automation.

The fundamental challenge with Google Flow AI:
  All video/image generation endpoints require reCAPTCHA Enterprise tokens.
  Tokens generated via `page.evaluate(grecaptcha.execute())` have LOW behavioral
  scores (Playwright automation is detected) → server returns 403.

  ONLY tokens generated by REAL UI button clicks pass → we must:
    1. Set up network listener BEFORE clicking
    2. Click the actual UI button (React event → grecaptcha.execute() called internally)
    3. Capture the API call from the interceptor
    4. Extract mediaName/mediaId from the response

This module provides:
  - UIInterceptor: attach to page, wait for API call results
  - Helpers for extracting VideoJob / GeneratedImage from captured responses
"""
from __future__ import annotations

import asyncio
import json
import logging
import time
from typing import Any, Optional

log = logging.getLogger(__name__)


class CapturedCall:
    """One intercepted aisandbox API request/response pair."""
    __slots__ = ("url", "tail", "method", "req", "resp", "status", "bearer", "ts")

    def __init__(self, url: str, method: str, req: dict, bearer: str):
        self.url     = url
        self.tail    = url.split("/")[-1].split("?")[0]
        self.method  = method
        self.req     = req
        self.resp: Optional[dict] = None
        self.status: Optional[int] = None
        self.bearer  = bearer
        self.ts      = time.monotonic()

    def __repr__(self):
        return f"<CapturedCall {self.tail} status={self.status}>"


class UIInterceptor:
    """
    Attach to a Playwright page to intercept all aisandbox-pa.googleapis.com calls.

    Usage pattern:
        interceptor = UIInterceptor()
        interceptor.attach(page)          # BEFORE clicking

        await flow_ui.click_extend(page)  # triggers real reCAPTCHA

        entry = await interceptor.wait_for("batchAsyncGenerateVideoExtendVideo")
        media_name = entry.resp["jobs"][0]["mediaId"]["mediaName"]
    """

    AISANDBOX_HOST = "aisandbox-pa.googleapis.com"

    def __init__(self, api=None):
        self._calls: list[CapturedCall] = []
        self._bearer: Optional[str] = None
        self._api = api
        self._attached = False

    # ── Attach ────────────────────────────────────────────────────────────────

    def attach(self, page) -> None:
        """Register request/response listeners on *page*.

        Safe to call multiple times on the same page — only attaches once
        per interceptor instance.
        """
        if self._attached:
            return
        self._attached = True

        page.on("request",  self._on_request)
        page.on("response", self._on_response)
        log.debug("UIInterceptor attached to %s", page.url[:60])

    # ── Listeners ─────────────────────────────────────────────────────────────

    def _on_request(self, request) -> None:
        if self.AISANDBOX_HOST not in request.url:
            return

        auth = request.headers.get("authorization", "") or request.headers.get("Authorization", "")
        if auth.startswith("Bearer "):
            self._bearer = auth[7:]
            # The UI request is the authoritative source on current Flow SPA
            # builds. Keep the API poller in sync before it sends its first
            # batchCheck request; cloned profiles often cannot mint ya29.
            if self._api is not None:
                try:
                    self._api.seed_bearer_token(self._bearer)
                except Exception:
                    log.debug("Could not seed FlowAPI Bearer from UI request", exc_info=True)

        try:
            body = request.post_data or ""
            req_data = json.loads(body) if body else {}
        except Exception:
            req_data = {}

        call = CapturedCall(
            url=request.url,
            method=request.method,
            req=req_data,
            bearer=self._bearer or "",
        )
        self._calls.append(call)
        log.debug("→ captured req  %s", call.tail)

    def _on_response(self, response) -> None:
        if self.AISANDBOX_HOST not in response.url:
            return

        tail = response.url.split("/")[-1].split("?")[0]

        async def _read(resp=response, t=tail):
            try:
                body = await resp.text()
                resp_data = json.loads(body) if body else {}
            except Exception:
                resp_data = {}

            # Match to the most recent unresolved call with same tail
            for call in reversed(self._calls):
                if call.tail == t and call.resp is None:
                    call.resp = resp_data
                    call.status = resp.status
                    log.debug("← captured resp %s [%d]", t, resp.status)
                    break

        # Schedule async read without blocking the listener.
        # Python 3.10+: use get_running_loop().create_task() which is
        # safe from sync callbacks inside a running event loop.
        try:
            asyncio.get_running_loop().create_task(_read())
        except RuntimeError:
            # Fallback: no running loop in this context
            try:
                asyncio.ensure_future(_read())
            except Exception:
                pass

    # ── Wait helpers ──────────────────────────────────────────────────────────

    async def wait_for(
        self,
        endpoint_tail: str,
        *,
        timeout: float = 120.0,
        poll_interval: float = 0.25,
        require_success: bool = False,
    ) -> CapturedCall:
        """
        Wait until an API call whose tail contains *endpoint_tail* gets a response.

        Args:
            endpoint_tail: substring to match against the URL tail,
                           e.g. "batchAsyncGenerateVideoExtendVideo"
            timeout:       seconds before raising TimeoutError
            require_success: if True, raises GenerationError on non-2xx status

        Returns:
            CapturedCall with .req and .resp populated.
        """
        from ._exceptions import GenerationTimeout, GenerationError

        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            match = self._find_completed(endpoint_tail)
            if match is not None:
                if require_success and match.status not in (200, 201):
                    err = match.resp or {}
                    msg = err.get("error", {}).get("message", str(match.status))
                    raise GenerationError(
                        f"{endpoint_tail} failed [{match.status}]: {msg}"
                    )
                return match
            await asyncio.sleep(poll_interval)

        raise GenerationTimeout(
            f"Timed out ({timeout}s) waiting for {endpoint_tail}. "
            f"Captured so far: {[c.tail for c in self._calls]}"
        )

    def _find_completed(self, tail_fragment: str) -> Optional[CapturedCall]:
        """Return most recent completed call containing *tail_fragment*."""
        for call in reversed(self._calls):
            if tail_fragment in call.tail and call.resp is not None:
                return call
        return None

    # ── Data extraction helpers ───────────────────────────────────────────────

    @staticmethod
    def extract_video_media_name(resp: dict) -> Optional[str]:
        """
        Extract mediaName from a video generation response.

        Response shapes (both confirmed from live capture):

        Shape 1 – batchAsyncGenerateVideoText / ExtendVideo / ReshootVideo / etc.:
            {
              "jobs": [{"mediaId": {"mediaName": "uuid-here", "projectId": "..."}}],
              ...
            }

        Shape 2 – some responses use "media" array:
            {"media": [{"name": "uuid-here", ...}]}
        """
        # Shape 1: jobs[].mediaId.mediaName
        jobs = resp.get("jobs", [])
        if jobs:
            media_id = jobs[0].get("mediaId", {})
            name = media_id.get("mediaName") or media_id.get("name")
            if name:
                return str(name)

        # Shape 2: media[].name
        media = resp.get("media", [])
        if media:
            name = media[0].get("name") or media[0].get("mediaName")
            if name:
                return str(name)

        # Shape 3: flat "mediaName" key
        name = resp.get("mediaName") or resp.get("name")
        if name:
            return str(name)

        return None

    @staticmethod
    def extract_image_urls(resp: dict) -> list[str]:
        """
        Extract FIFE thumbnail URLs from a batchGenerateImages response.

        Confirmed response structure:
            {
              "generatedImages": [
                {
                  "image": {"imageBytes": "...", "mimeType": "image/jpeg"},
                  "fifeUrl": "https://lh3.googleusercontent.com/...",
                  "mediaName": "projects/.../flowMedia/..."
                }
              ]
            }
        """
        urls = []
        for img in resp.get("generatedImages", []):
            url = img.get("fifeUrl") or img.get("fife_url")
            if url:
                urls.append(url)
        return urls

    @staticmethod
    def extract_image_media_names(resp: dict) -> list[str]:
        """Extract mediaName list from a batchGenerateImages response."""
        names = []
        for img in resp.get("generatedImages", []):
            name = img.get("mediaName") or img.get("name")
            if name:
                names.append(str(name))
        return names

    # ── State helpers ─────────────────────────────────────────────────────────

    @property
    def bearer(self) -> Optional[str]:
        """Most recently seen Bearer token from captured requests."""
        return self._bearer

    def clear(self) -> None:
        """Reset all captured calls (keep bearer token)."""
        self._calls.clear()
        log.debug("UIInterceptor cleared")

    def all_tails(self) -> list[str]:
        """All captured endpoint tails (for debugging)."""
        return [c.tail for c in self._calls]

    def pending(self) -> list[CapturedCall]:
        """Calls that have been sent but not yet received a response."""
        return [c for c in self._calls if c.resp is None]

    def __repr__(self):
        return (
            f"<UIInterceptor calls={len(self._calls)} "
            f"bearer={'✓' if self._bearer else '✗'}>"
        )
