import React from 'react'
import { api } from '@/features/project/project.api'
import type { ProjectMediaAsset } from '@/features/project/project.types'
import { ScrollArea } from '@/shared/ui/scroll-area'

type Props = { projectId: string; busy: boolean; onApplySrt: (asset: ProjectMediaAsset) => void | Promise<void> }
const kindLabel: Record<ProjectMediaAsset['kind'], string> = { video: 'Video', audio: 'Audio', image: 'Ảnh', srt: 'SRT', lut: 'LUT' }

export function EditorMediaPanel({ projectId, busy, onApplySrt }: Props) {
  const inputRef = React.useRef<HTMLInputElement>(null)
  const [items, setItems] = React.useState<ProjectMediaAsset[]>([])
  const [error, setError] = React.useState('')
  const [loading, setLoading] = React.useState(true)
  const reload = React.useCallback(() => { setLoading(true); void api.mediaAssets(projectId).then((r) => setItems(r.items)).catch((e) => setError(e instanceof Error ? e.message : 'Không tải được Media')).finally(() => setLoading(false)) }, [projectId])
  React.useEffect(() => { reload() }, [reload])
  const upload = async (files: FileList | null) => { if (!files?.length || busy) return; setError(''); try { for (const file of Array.from(files)) { const r = await api.uploadMediaAsset(projectId, file); setItems((prev) => [...prev, r.item]) } } catch (e) { setError(e instanceof Error ? e.message : 'Không nhập được file') } }
  return <ScrollArea className="h-full scrollbar-hidden"><div className="space-y-3 p-3"><div className="border-b border-border pb-1 text-sm text-muted-foreground">Media</div><input ref={inputRef} className="hidden" type="file" multiple accept="video/*,audio/*,image/*,.srt,.cube" onChange={(e) => { void upload(e.target.files); e.currentTarget.value = '' }} /><button type="button" disabled={busy} className="w-full rounded-md border border-dashed border-primary/50 bg-primary/5 px-3 py-4 text-xs font-medium text-primary hover:bg-primary/10 disabled:opacity-50" onClick={() => inputRef.current?.click()}>Nhập video, audio, ảnh, SRT hoặc LUT</button>{error && <p className="text-[11px] text-destructive">{error}</p>}{loading ? <p className="text-xs text-muted-foreground">Đang tải…</p> : items.length === 0 ? <p className="py-4 text-center text-xs text-muted-foreground">Chưa có file media.</p> : items.map((item) => <div key={item.id} draggable={item.kind !== 'srt' && item.kind !== 'lut'} onDragStart={(e) => { e.dataTransfer.setData('application/x-zm_ai_tool-asset', JSON.stringify(item)); e.dataTransfer.effectAllowed = 'copy' }} className="flex gap-2 rounded-md border border-border bg-background p-2 text-left"><div className="flex size-14 shrink-0 items-center justify-center overflow-hidden rounded bg-muted text-[10px] font-medium text-muted-foreground">{item.kind === 'video' || item.kind === 'image' ? <img className="size-full object-cover" src={`/api/projects/${projectId}/assets/${item.id}/thumbnail`} alt={`Thumbnail ${item.name}`} /> : item.kind === 'audio' ? 'AUDIO' : item.kind === 'lut' ? 'LUT' : 'SRT'}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-1"><span className="rounded bg-accent px-1.5 py-0.5 text-[10px] font-medium">{kindLabel[item.kind]}</span>{typeof item.duration === 'number' && <span className="text-[10px] text-muted-foreground">{item.duration.toFixed(1)}s</span>}</div><p className="mt-1 truncate text-xs">{item.name}</p><div className="mt-1">{item.kind === 'srt' ? <button type="button" className="text-[11px] font-medium text-primary hover:underline" onClick={() => void onApplySrt(item)}>Áp dụng</button> : <button type="button" className="text-[11px] text-muted-foreground hover:text-destructive" onClick={() => void api.deleteMediaAsset(projectId, item.id).then(reload).catch((e) => setError(e instanceof Error ? e.message : 'Không xóa được'))}>Xóa</button>}</div></div></div>)}</div></ScrollArea>
}
